from __future__ import annotations
from pathlib import Path
from typing import Protocol

class Storage(Protocol):
    def remove_prefix(self, *, remote_prefix: str) -> None: ...
    def upload_dir(self, *, local_dir: Path, remote_prefix: str) -> None: ...
    def list_objects(self, *, remote_prefix: str) -> list[str]: ...
    def download_prefix(self, *, remote_prefix: str, local_dir: Path, max_workers: int = 6) -> None: ...
    def download_file(self, *, remote_path: str, local_path: Path) -> Path: ...